// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrc7hOLIsfMfKE_kVJN5EJalgm__Q3_oc',
    appId: '1:27245415534:web:4769092b7a7dec98846a7f',
    messagingSenderId: '27245415534',
    projectId: 'fir-try1-c0ce2',
    authDomain: 'fir-try1-c0ce2.firebaseapp.com',
    storageBucket: 'fir-try1-c0ce2.firebasestorage.app',
    measurementId: 'G-J3RPWBFYVV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJBHwbUzZtWaziI4u90lcM2l_MCeCnUPs',
    appId: '1:27245415534:ios:b8540bde19f2dcf5846a7f',
    messagingSenderId: '27245415534',
    projectId: 'fir-try1-c0ce2',
    storageBucket: 'fir-try1-c0ce2.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrc7hOLIsfMfKE_kVJN5EJalgm__Q3_oc',
    appId: '1:27245415534:web:974e4f5879774a92846a7f',
    messagingSenderId: '27245415534',
    projectId: 'fir-try1-c0ce2',
    authDomain: 'fir-try1-c0ce2.firebaseapp.com',
    storageBucket: 'fir-try1-c0ce2.firebasestorage.app',
    measurementId: 'G-R5WGQPRQBZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJBHwbUzZtWaziI4u90lcM2l_MCeCnUPs',
    appId: '1:27245415534:ios:b8540bde19f2dcf5846a7f',
    messagingSenderId: '27245415534',
    projectId: 'fir-try1-c0ce2',
    storageBucket: 'fir-try1-c0ce2.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr1KOL_lw8pYzXo3-Tq6k4bKckYrx9blo',
    appId: '1:27245415534:android:05e6bf53ba82a273846a7f',
    messagingSenderId: '27245415534',
    projectId: 'fir-try1-c0ce2',
    storageBucket: 'fir-try1-c0ce2.firebasestorage.app',
  );
}
